#!/usr/bin/python3
#-*- coding:utf-8 -*-
import os
from flask import Flask,make_response
from flask import render_template

app = Flask(__name__)

@app.route('/<path>')
def today(path):
    base_dir = os.path.dirname(__file__)
    resp = make_response(open(os.path.join(base_dir, path)).read())
    resp.headers["Content-type"]="charset=UTF-8"
    return resp
"""
@app.route('/')
def show():
    return render_template('index.html')
"""
if __name__ == '__main__':
    app.run(host='192.168.1.104',port=5000,debug=True)
